#!/bin/bash
# CHANGELOG Generator
# Auto-generates structured CHANGELOG.md from git history

set -e

REPO_URL=$(git remote get-url origin 2>/dev/null || echo "local")
LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
OUTPUT_FILE="CHANGELOG.md"

echo "🔍 Fetching commits since last tag..."

if [ -z "$LATEST_TAG" ]; then
    COMMITS=$(git log --pretty=format:"%s" --reverse)
    echo "⚠️  No tags found. Using all commits."
else
    COMMITS=$(git log "${LATEST_TAG}..HEAD" --pretty=format:"%s" --reverse)
    echo "✅ Found tag: $LATEST_TAG"
fi

if [ -z "$COMMITS" ]; then
    echo "❌ No new commits found since last tag."
    exit 0
fi

# Categorize commits
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""

while IFS= read -r line; do
    lower=$(echo "$line" | tr '[:upper:]' '[:lower:]')
    
    if echo "$lower" | grep -qE "^(feat|add|new|introduce|implement)"; then
        ADDED="${ADDED}- ${line}\n"
    elif echo "$lower" | grep -qE "^(fix|bugfix|hotfix|resolve|patch)"; then
        FIXED="${FIXED}- ${line}\n"
    elif echo "$lower" | grep -qE "^(remove|delete|drop|deprecate)"; then
        REMOVED="${REMOVED}- ${line}\n"
    elif echo "$lower" | grep -qE "^(update|change|modify|refactor|improve|enhance|perf)"; then
        CHANGED="${CHANGED}- ${line}\n"
    else
        CHANGED="${CHANGED}- ${line}\n"
    fi
done <<< "$COMMITS"

# Generate CHANGELOG.md
cat > "$OUTPUT_FILE" << EOF
# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased]

$(if [ -n "$ADDED" ]; then echo "### Added"; echo; echo -e "$ADDED"; fi)
$(if [ -n "$CHANGED" ]; then echo "### Changed"; echo; echo -e "$CHANGED"; fi)
$(if [ -n "$FIXED" ]; then echo "### Fixed"; echo; echo -e "$FIXED"; fi)
$(if [ -n "$REMOVED" ]; then echo "### Removed"; echo; echo -e "$REMOVED"; fi)
---

Generated by [CHANGELOG Generator](https://github.com/claude-builders-bounty/claude-builders-bounty)
EOF

echo "✅ CHANGELOG.md generated successfully!"
echo "📄 Output: $OUTPUT_FILE"
